server:
  port: 9000

spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    application:
        name: rabbitmq-sample

rabbitMQ:
    host: 10.160.10.60
    port: 5672
    username: o2o-user
    password: o2o-password
    vhost: o2o-app-host